# Generated by Django 4.0.4 on 2022-06-30 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
