# Generated by Django 4.0.4 on 2022-07-04 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
