# Generated by Django 4.0.4 on 2022-07-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_dat',
            new_name='updated_date',
        ),
    ]
